name: Prefixes
version: '${project.version}'
main: me.sourceform.prefixes.CustomPrefixPlugin
api-version: '1.21'
authors: [SourceForm]
description: Plugin to add prefixes to players on a minecraft server
website: https://github.com/SourceForm

commands:
  setprefix:
    description: Set a prefix for a player
    usage: /setprefix <player> <prefix>
    permission: prefixes.setprefix
    permission-message: Get an administrator to perform this command.

permissions:
  prefixes.setprefix:
    description: Allows the user to assign prefixes to players
    default: true
